### ISSUE TITLE
Incorrect links in readme

### ISSUE THREAD

**Issue by petrbroz** [autodesk-platform-services/aps-sdk-net#23]
The links in the [Nuget Packages](https://github.com/autodesk-platform-services/aps-sdk-net?tab=readme-ov-file#nuget-packages) section of the readme seem to all point to the github repo itself. Is that expected?

**Comment by antonioortizpola** [comment]
Also, the documentation still points to Autodesk.Forge. For example, [Simple viewer](https://tutorials.autodesk.io/tutorials/simple-viewer/) 
![image](https://github.com/autodesk-platform-services/aps-sdk-net/assets/11655127/0076fb34-531b-49b2-953d-8503727f221a).

Another excellent missing source is the [old documentation](https://github.com/Autodesk-Forge/forge-api-dotnet-client/tree/master/docs), but I can not find it anymore.

**Comment by tylerwarner33** [comment]
@sajith-subramanian this issue looks like it can be closed.

In response to @petrbroz, the links have been updated in #40 (approved & merged), with a name correction included in #77 (waiting for approval).

In response to @antonioortizpola, the documentation for the tutorials website is hosted in another [repo](https://github.com/autodesk-platform-services/aps-tutorials-website), but has also been updated with the SDK Nuget Packages as seen [here](https://tutorials.autodesk.io/tutorials/simple-viewer/setup).
