### ISSUE TITLE
GetRefreshTokenAsync questions

### ISSUE THREAD

**Issue by petrbroz** [autodesk-platform-services/aps-sdk-net#25]
The naming of the `GetRefreshTokenAsync` method is a bit confusing. It sounds like the method is supposed to _retrieve_ a refresh token while it is in fact used to _refresh_ a token. Also, the `GetThreeLeggedTokenAsync` method also returns a refresh token. Shouldn't the method be called `RefreshTokenAsync` instead?

Also, I was expecting both `GetThreeLeggedTokenAsync` and `GetRefreshTokenAsync` to return the same type of object as a result but that's not the case. `GetThreeLeggedTokenAsync` returns a `ThreeLeggedToken` object with properties like `RefreshToken`, and `GetRefreshTokenAsync` returns a `RefreshToken` object with a property called `_RefreshToken`. Why the underscore?

**Comment by sajith-subramanian** [comment]
Fixed in latest version.  The method for refreshing the token now returns an instance of a Three Legged Token.
