### ISSUE TITLE
Compile sources with documentation.

### ISSUE THREAD

**Issue by antonioortizpola** [autodesk-platform-services/aps-sdk-net#27]
While there is documentation on the source code, the same can not be found on the nuget, because of this, we are not able to make an efficient use of the documentation.
![image](https://github.com/autodesk-platform-services/aps-sdk-net/assets/11655127/2853ca99-dba7-46ea-a574-7c10d078cc44)

**Comment by sajith-subramanian** [comment]
Thanks, @antonioortizpola. We are working on the documentation. Will add this to the list.

**Comment by sajith-subramanian** [comment]
The latest version of the nuget packages address this issue.
