### ISSUE TITLE
DataManagement - VersionsDataAttributes does not contain FileType and other properties

### ISSUE THREAD

**Issue by austincrft** [autodesk-platform-services/aps-sdk-net#30]
The REST API documentation here specifies a `fileType` property on `attributes`

[GET projects/:project_id/items/:item_id/versions | Data Management API | Autodesk Platform Services](https://aps.autodesk.com/en/docs/data/v2/reference/http/projects-project_id-items-item_id-versions-GET/)

![image](https://github.com/autodesk-platform-services/aps-sdk-net/assets/3616544/19a8440a-0f2f-4bc7-84e5-d664f4dfe20b)

Here you can see my call to `DataManagementClient.GetItemVersionsAsync` does not return the `FileType` property

![image](https://github.com/autodesk-platform-services/aps-sdk-net/assets/3616544/059e9865-fe7c-4979-800e-87499af04178)

**Comment by austincrft** [comment]
I have just tested that the data is being returned properly in the JSON response, it is just not present in the POCO.

This is also missing from the POCO but present in the JSON response: `data.relationships.derivatives`

**Comment by sajith-subramanian** [comment]
Hi @austincrft - I have logged this issue for further investigation.

**Comment by yiskang** [comment]
Hi Team,

I found one more missing field, `attributes.ViewableGuid`.

Sample code: https://github.com/autodesk-platform-services/aps-acc-locations-manager/blob/main/Autodesk/Libs/AccDataUtil.cs#L106

And other possible missing fields here: https://github.com/autodesk-platform-services/aps-bim360-assets-viewer/blob/main/bim360assets/Controllers/HubsController.cs#L204

**Comment by sajith-subramanian** [comment]
This has been fixed as part of this release: https://www.nuget.org/packages/Autodesk.DataManagement/2.0.0-beta3
Please review it and let us know in case of any issues. Thanks!
