### ISSUE TITLE
OssClient.DeleteObjectAsync() & OssClient.GetObjectDetailsAsync() NullReferenceException

### ISSUE THREAD

**Issue by tylerwarner33** [autodesk-platform-services/aps-sdk-net#62]
Hello APS Team & @sajith-subramanian,

I can successfully create a new object in the specified bucket using a local file as shown. This can be verified using the [OSS Manager Tool](https://oss-manager.autodesk.io/#)
![Screenshot 2024-07-19 051727](https://github.com/user-attachments/assets/450d0ca1-7fc4-4a1f-b302-0c38947777a9).

But, I'm unable to get the details for that object or to delete that object. The call is being thrown with a 'System.NullReferenceException' without any details. I've tried using the name of the object, the objectId & the objectKey without success. Access token & bucket key are the same as shown in the upload image, so those are not null.
![Screenshot 2024-07-19 052010](https://github.com/user-attachments/assets/d6160137-172b-4ca0-b06c-0587627d69ef)

All scopes were added to the token to ensure that wasn't the issue, even though it would have thrown a different error for that.
![Screenshot 2024-07-19 053807](https://github.com/user-attachments/assets/eb406a20-7753-4b9b-9f72-4ca29d622465)

What is the proper way to successfully execute these methods?

Thanks,
Tyler

**Comment by tylerwarner33** [comment]
This seems to be directly related to Autodesk.Oss Version 1.1.0, see [StackOverflow post](https://stackoverflow.com/questions/78770178/autodesk-platform-services-forge-net-sdk-ossclient-deleteobjectasync-ossc).

**Comment by sajith-subramanian** [comment]
Hi @tylerwarner33, this issue has been identified and we will be updating the Oss package with the fix soon. Thanks for reporting!

**Comment by sajith-subramanian** [comment]
Hi @tylerwarner33 , can you please test on the updated package ([Link](https://www.nuget.org/packages/Autodesk.Oss/1.1.1)) and confirm if everything works as expected? Thanks!

**Comment by tylerwarner33** [comment]
Hello @sajith-subramanian, sorry for the delay. The project was put on hold. Yes, the new Nuget Package version works as expected, thanks!
