### ISSUE TITLE
HookData object does not contain any HookAttributes like ProjectId

### ISSUE THREAD

**Issue by ApiObjects** [autodesk-platform-services/aps-sdk-net#94]
There is no way of obtaining HookAttributes of a webhook from the HookData object.

Example:
I'm trying to let users create a webhook for a specific revit file. When they open a revit file in the viewer i should be able to check if there is a webhook active for that specific revit file. So to specify the revit file i save the urn of my model inside the HookAttributes when registering a webhook. But when i try to obtain the existing webhooks i can't retreive it. For now i will use HookData.Scope to get the folderId but that is limited.

**Comment by sajith-subramanian** [comment]
Thanks for reporting this @ApiObjects. This has been logged in our system for a fix.

**Comment by sajith-subramanian** [comment]
@ApiObjects - This fix has been released as part of this version - https://www.nuget.org/packages/Autodesk.Webhooks/2.0.0
Please try it out and let us know in case of any issues. Thanks
