### ISSUE TITLE
x-ads-force value is sent in header as True instead of true and gets ignored by MD

### ISSUE THREAD

**Issue by adamenagy** [autodesk-platform-services/aps-sdk-net#95]
The model derivative service seems to ignore x-ads-force if it starts with a capital T for true.
I checked with "Charles" app to see what the SDK was sending (i.e. "True"), and verified in Insomnia that if the value is "True" instead of "true" it gets ignored - I can see it from asking for the manifest straight after the submitting the job and see that the progress is "complete"

**Comment by sajith-subramanian** [comment]
Thanks for reporting this issue @adamenagy. I have logged this issue for a fix.

**Comment by sajith-subramanian** [comment]
@adamenagy - This has now been fixed in the latest release. Let us know in case of any issues.
For quick reference:  `dotnet add package Autodesk.ModelDerivative --version 2.0.0-beta3`
